name: Test

on:
  pull_request:

  workflow_dispatch: # Can run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/init

      - run: bun run test
